const ago = (hours) => new Date(Date.now() - hours * 3600 * 1000).toISOString();
const later = (hours) => new Date(Date.now() + hours * 3600 * 1000).toISOString();
const pic = (id, w = 1080, h = 1080) => `https://picsum.photos/id/${id}/${w}/${h}`;

export const users = [
  {
    id: 1,
    username: "demo",
    email: "demo@insta.local",
    password: "demo1234",
    full_name: "데모 사용자",
    bio: "인스타그램 클론 데모 계정입니다.",
    website: "https://example.com",
    avatar_url: pic(64, 400, 400),
  },
  {
    id: 2,
    username: "travel_mia",
    email: "mia@insta.local",
    password: "demo1234",
    full_name: "박미아",
    bio: "여행 기록. 다음 목적지는 제주.",
    website: "",
    avatar_url: pic(1015, 400, 400),
  },
  {
    id: 3,
    username: "foodie_ken",
    email: "ken@insta.local",
    password: "demo1234",
    full_name: "최켄",
    bio: "맛집 탐험가 | 서울",
    website: "",
    avatar_url: pic(292, 400, 400),
  },
  {
    id: 4,
    username: "studio_ara",
    email: "ara@insta.local",
    password: "demo1234",
    full_name: "김아라",
    bio: "사진 · 패션 · 일상",
    website: "https://ara.studio",
    avatar_url: pic(338, 400, 400),
  },
  {
    id: 5,
    username: "nightowl",
    email: "owl@insta.local",
    password: "demo1234",
    full_name: "이노아",
    bio: "도시의 밤을 담습니다.",
    website: "",
    avatar_url: pic(1060, 400, 400),
  },
  {
    id: 6,
    username: "plant_jun",
    email: "jun@insta.local",
    password: "demo1234",
    full_name: "서준",
    bio: "식물과 함께하는 하루 #식물",
    website: "",
    avatar_url: pic(167, 400, 400),
    is_private: true,
  },
  {
    id: 7,
    username: "test",
    email: "test@gmail.com",
    password: "12345",
    full_name: "테스트 사용자",
    bio: "모든 페이지 확인용 테스트 계정입니다.",
    website: "",
    avatar_url: pic(237, 400, 400),
  },
];

export const posts = [
  {
    id: 1,
    user_id: 2,
    images: [pic(1015), pic(1016), pic(1019)],
    caption: "한옥 골목 아침. #여행 #서울",
    location: "북촌, 서울",
    created_at: ago(4),
  },
  {
    id: 2,
    user_id: 2,
    images: [pic(1016)],
    caption: "바다 위 노을이 전부였다. #여행 #노을",
    location: "부산",
    created_at: ago(10),
  },
  {
    id: 3,
    user_id: 3,
    images: [pic(292)],
    caption: "이 라멘 한 그릇이면 충분. #맛집 #라멘",
    location: "성수",
    created_at: ago(12),
  },
  {
    id: 4,
    user_id: 3,
    images: [pic(429)],
    caption: "크로와상은 버터가 답이다. #베이커리",
    location: "한남",
    created_at: ago(18),
  },
  {
    id: 5,
    user_id: 4,
    images: [pic(338), pic(349)],
    caption: "오늘의 무드. #패션 #데일리룩",
    location: "성수",
    created_at: ago(22),
  },
  {
    id: 6,
    user_id: 4,
    images: [pic(433)],
    caption: "빛이 들어오는 자리. #스튜디오",
    location: "서울",
    created_at: ago(28),
  },
  {
    id: 7,
    user_id: 5,
    images: [pic(1060)],
    caption: "한강 다리 불빛. #밤 #도시",
    location: "한강",
    created_at: ago(30),
  },
  {
    id: 8,
    user_id: 5,
    images: [pic(1074)],
    caption: "비 온 뒤 아스팔트. #밤",
    location: "강남",
    created_at: ago(36),
  },
  {
    id: 9,
    user_id: 6,
    images: [pic(167)],
    caption: "새 잎이 났다. #식물",
    location: "집",
    created_at: ago(40),
  },
  {
    id: 10,
    user_id: 1,
    images: [pic(1011)],
    caption: "클론 앱 첫 게시물. #안녕",
    location: "서울",
    created_at: ago(8),
  },
  {
    id: 11,
    user_id: 1,
    images: [pic(1018)],
    caption: "피드가 이렇게 채워집니다. #일상",
    location: "",
    created_at: ago(2),
  },
  {
    id: 12,
    user_id: 2,
    images: [pic(1036)],
    caption: "창밖 풍경만으로 충분한 날. #주말",
    location: "제주",
    created_at: ago(48),
  },
  {
    id: 13,
    user_id: 7,
    images: [pic(237), pic(238)],
    caption: "테스트 계정으로 올린 첫 사진. #테스트",
    location: "서울",
    created_at: ago(6),
  },
  {
    id: 14,
    user_id: 7,
    images: [pic(287)],
    caption: "저장·댓글·좋아요를 확인하는 게시물입니다. #일상",
    location: "성수",
    created_at: ago(1),
  },
];

export const comments = [
  { id: 1, post_id: 1, user_id: 1, content: "여기 진짜 예쁘다", created_at: ago(3) },
  { id: 2, post_id: 3, user_id: 2, content: "다음에 같이 가요", created_at: ago(8) },
  { id: 3, post_id: 5, user_id: 5, content: "색감이 좋다", created_at: ago(16) },
  { id: 4, post_id: 10, user_id: 4, content: "환영해요!", created_at: ago(6) },
  { id: 5, post_id: 1, user_id: 7, content: "테스트 계정에서 남긴 댓글입니다.", created_at: ago(2) },
  { id: 6, post_id: 13, user_id: 2, content: "테스트 피드 잘 보여요!", created_at: ago(4) },
  { id: 7, post_id: 14, user_id: 3, content: "저장 탭도 확인해 보세요.", created_at: ago(1) },
];

export const likes = [
  [1, 1],
  [3, 1],
  [1, 3],
  [2, 3],
  [1, 5],
  [1, 7],
  [2, 10],
  [7, 1],
  [7, 3],
  [7, 5],
  [2, 13],
  [3, 14],
];

export const saves = [
  [1, 1],
  [1, 5],
  [7, 1],
  [7, 5],
];

export const follows = [
  [1, 2],
  [1, 3],
  [1, 4],
  [1, 5],
  [2, 1],
  [2, 4],
  [3, 1],
  [3, 2],
  [4, 5],
  [4, 1],
  [5, 4],
  [5, 6],
  [6, 1],
  [6, 3],
  [7, 2],
  [7, 3],
  [7, 4],
  [7, 5],
  [7, 6],
  [2, 7],
  [3, 7],
];

export const stories = [
  { id: 1, user_id: 1, image_url: pic(1018, 540, 960), created_at: ago(2), expires_at: later(22) },
  { id: 2, user_id: 2, image_url: pic(1015, 540, 960), created_at: ago(3), expires_at: later(21) },
  { id: 3, user_id: 3, image_url: pic(292, 540, 960), created_at: ago(5), expires_at: later(19) },
  { id: 4, user_id: 4, image_url: pic(338, 540, 960), created_at: ago(6), expires_at: later(18) },
  { id: 5, user_id: 7, image_url: pic(237, 540, 960), created_at: ago(1), expires_at: later(23) },
];

export const notifications = [
  { id: 1, user_id: 1, actor_id: 4, type: "comment", post_id: 10, is_read: false, created_at: ago(1) },
  { id: 2, user_id: 1, actor_id: 2, type: "like", post_id: 10, is_read: false, created_at: ago(2) },
  { id: 3, user_id: 1, actor_id: 2, type: "message", post_id: null, is_read: false, created_at: ago(5) },
  { id: 4, user_id: 1, actor_id: 6, type: "follow", post_id: null, is_read: false, created_at: ago(24) },
  { id: 5, user_id: 7, actor_id: 2, type: "like", post_id: 13, is_read: false, created_at: ago(3) },
  { id: 6, user_id: 7, actor_id: 2, type: "comment", post_id: 13, is_read: false, created_at: ago(4) },
  { id: 7, user_id: 7, actor_id: 3, type: "follow", post_id: null, is_read: false, created_at: ago(8) },
  { id: 8, user_id: 7, actor_id: 2, type: "message", post_id: null, is_read: false, created_at: ago(2) },
];

export const messages = [
  { id: 1, sender_id: 2, receiver_id: 1, content: "피드 잘 봤어요. 여행 사진 더 올려요!", post_id: null, is_read: false, created_at: ago(5) },
  { id: 2, sender_id: 1, receiver_id: 2, content: "고마워요 미아!", post_id: null, is_read: true, created_at: ago(4) },
  { id: 3, sender_id: 2, receiver_id: 7, content: "테스트 계정으로 메시지함을 확인해 보세요.", post_id: null, is_read: false, created_at: ago(3) },
  { id: 4, sender_id: 7, receiver_id: 2, content: "네, 잘 보여요!", post_id: null, is_read: true, created_at: ago(2) },
];

export const store = {
  users,
  posts,
  comments,
  likes,
  saves,
  follows,
  stories,
  notifications,
  messages,
  nextIds: { user: 8, post: 15, comment: 8, story: 6, notif: 9, message: 5 },
};
